//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Информационная_система_медицинской_клиники
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoices
    {
        public int InvoiceID { get; set; }
        public string PatientName { get; set; }
        public string ServiceName { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Statuss { get; set; }
    
        public virtual Patients Patients { get; set; }
        public virtual Servicess Servicess { get; set; }
    }
}
